// ============================================================
// 📄 Your Resume Profiles — extracted from your PDFs
// ============================================================

const profiles = [
  {
    id: 'ai',
    name: '🤖 AI / ML Specialist',
    titles: [
      'AI Engineer', 'Machine Learning Engineer', 'Prompt Engineer',
      'AI Agent Developer', 'LLM Engineer', 'AI Specialist',
      'Data Scientist', 'AI Ops Engineer', 'Gen AI Engineer',
      'AI Product Developer', 'Junior AI Engineer',
      'Associate AI Engineer', 'AI Research Assistant',
      'AI Developer', 'AI Consultant', 'AI Solutions Engineer',
      'No Code AI Developer', 'AI Workflow Specialist',
      'AI Integration Engineer', 'Machine Learning Intern',
      'AI Product Manager', 'AI Tester', 'AI Quality Assurance',
      'AI Content Creator', 'AI Video Producer', 'AI Operations',
      // Vibe Coding titles
      'Vibe Coder', 'AI-Assisted Developer', 'AI Coding Specialist',
      'AI Prototyper', 'AI Workflow Builder',
      'Agentic Developer', 'Cursor Developer',
      // Web3 + AI titles
      'Web3 AI Developer', 'Web3 AI Engineer',
      'Blockchain AI Engineer', 'Smart Contract Developer',
      'Solidity Developer', 'dApp Developer',
      'Blockchain Developer', 'Web3 Developer',
      'On-Chain AI Developer', 'DeFi Developer',
      'Web3 Protocol Developer', 'Crypto AI Developer'
    ],
    keywords: [
      'prompt engineering', 'vibe coding', 'machine learning',
      'AI agent', 'LLM', 'fine-tuning', 'generative AI',
      'workflow automation', 'data annotation', 'ChatGPT',
      'Claude', 'AI development', 'NLP', 'deep learning',
      'computer vision', 'LangChain', 'RAG', 'AI integration',
      'AI video', 'no code', 'low code', 'AI tools',
      'API integration', 'automation', 'AI pipeline',
      'AI strategy', 'AI implementation', 'Hugging Face',
      'OpenAI API', 'AI content generation',
      'natural language processing', 'text generation',
      'AI-assisted', 'AI training', 'model evaluation',
      'AI testing', 'prototyping', 'AI proof of concept',
      'AI curriculum', 'AI documentation',
      // Vibe Coding keywords
      'vibe coding', 'ai-assisted coding', 'cursor', 'copilot',
      'claude code', 'prompt to code', 'ai prototyping',
      'rapid prototyping', 'agentic development',
      'ai workflow', 'ai ide', 'ai developer tools',
      'replit', 'windsurf', 'ai pair programming',
      // Web3 + AI keywords
      'web3', 'blockchain', 'solidity', 'smart contract',
      'dapp', 'defi', 'ethereum', 'solana', 'sui',
      'move language', 'web3 development', 'on-chain',
      'decentralized', 'tokenomics', 'nft', 'dao',
      'web3 infrastructure', '0g', 'zero gravity',
      'ai agent blockchain', 'crypto', 'web3 protocol',
      'chainlink', 'oracle', 'layer 2', 'rollup'
    ],
    skills: [
      'Prompt Engineering', 'Vibe Coding', 'Machine Learning',
      'AI Agent Development', 'Gen AI Tools', 'LLM Finetuning',
      'Workflow Automation', 'Data Annotation', 'Generative AI',
      'No Code / Low Code AI', 'API Integration',
      'AI Content Production', 'AI Consultation',
      'Hugging Face Models', 'OpenAI / Claude APIs'
    ],
    // Keywords that REDUCE match probability — jobs requiring these are likely rejects
    rejectionKeywords: [
      'phd required', 'phd preferred', 'phd in computer science',
      'masters degree required', 'ms degree required',
      'doctorate', 'publication record', 'peer reviewed',
      '10+ years', '10+ year', 'ten years',
      '15+ years', '15+ year', 'fifteen years',
      'cissp', 'aws certified', 'google cloud certified',
      'medical license', 'bar exam', 'bar admission',
      'security clearance', 'active clearance', 'ts/sci',
      'us person', 'us citizen', 'green card',
      'must be a us', 'us work authorization required',
      'senior staff', 'principal engineer', 'head of engineering',
      'director of engineering', 'vp of engineering',
      'on-site', 'in-office', 'must relocate',
      'fortune 500', 'big 4', 'management consulting'
    ],
    minSalary: 50,
    minMonthly: 10000,
    maxExpYears: 5,       // Isaac is entry-mid, penalize jobs needing >5yr
    portfolio: 'https://tinyurl.com/Ai-Generalist-Portfolio'
  },
  {
    id: 'writing',
    name: '✍️ Content & Copywriting Specialist',
    titles: [
      'Copywriter', 'Content Writer', 'Content Strategist',
      'SEO Writer', 'Technical Writer', 'Web3 Writer',
      'Social Media Manager', 'Content Marketing Specialist',
      'Brand Storyteller', 'Community Manager',
      'AI Content Creator', 'Video Scriptwriter',
      'Junior Copywriter', 'Associate Content Writer',
      'Content Assistant', 'Social Media Coordinator',
      'Content Producer', 'Digital Content Writer',
      'Blog Writer', 'Ghostwriter', 'UX Writer',
      'Content Editor', 'Newsletter Writer',
      'AI Content Editor', 'Prompt Copywriter',
      'Marketing Copywriter', 'Brand Copywriter',
      'Content Marketing Assistant', 'Communication Specialist',
      // Web3 + AI Writing titles
      'Crypto Writer', 'Crypto Copywriter',
      'Blockchain Content Writer', 'Blockchain Copywriter',
      'DeFi Content Writer', 'DeFi Copywriter',
      'Web3 Content Strategist', 'Web3 Copywriter',
      'NFT Writer', 'NFT Copywriter',
      'DAO Content Creator', 'Web3 Community Manager',
      'Crypto Content Creator', 'Blockchain Journalist',
      'Web3 Technical Writer', 'Crypto Education Writer',
      'Tokenomics Writer', 'Web3 Social Media Manager'
    ],
    keywords: [
      'copywriting', 'content strategy', 'SEO writing',
      'social media', 'content marketing', 'brand voice',
      'storytelling', 'AI video production', 'Canva',
      'community management', 'web3', 'crypto writing',
      'email marketing', 'landing page', 'content calendar',
      'blog writing', 'ghostwriting', 'UX writing',
      'newsletter', 'editing', 'proofreading',
      'content management', 'WordPress', 'social media management',
      'content creation', 'copy editing', 'brand messaging',
      'tone of voice', 'content production',
      'AI content', 'prompt writing', 'content optimization',
      'A/B testing', 'content analytics', 'audience growth',
      // Vibe Coding content keywords
      'vibe coding', 'ai-assisted writing', 'ai content',
      'prompt engineering writing', 'ai copywriting',
      // Web3 + AI Writing keywords
      'crypto', 'cryptocurrency', 'blockchain', 'web3',
      'nft', 'defi', 'dao', 'tokenomics',
      'solidity', 'smart contract', 'decentralized',
      'ethereum', 'solana', 'sui', 'layer 2',
      'web3 content', 'crypto content', 'blockchain content',
      'defi content', 'nft content', 'crypto education',
      'web3 education', 'blockchain education',
      'dao communication', 'web3 community',
      'crypto marketing', 'web3 marketing', 'token',
      '0g', 'zero gravity', 'ai agent', 'on-chain',
      'xikki', 'veridd', 'decentralized identity'
    ],
    skills: [
      'Copywriting & SEO', 'Content Strategy', 'Social Media Management',
      'Storytelling & Brand Voice', 'AI Video Production',
      'Canva & Visual Design', 'Community Management',
      'Web3 Technical Writing', 'Prompt Engineering',
      'Newsletter Production', 'Content Editing',
      'Brand Messaging', 'Content Analytics',
      'Web3 Copywriting', 'Crypto Content Strategy',
      'Blockchain Education', 'DAO Communications',
      'Vibe Coding Content', 'AI-Assisted Writing'
    ],
    rejectionKeywords: [
      'phd', 'doctorate', 'masters degree',
      '10+ years', '10+ year', 'ten years',
      '15+ years', '15+ year',
      'cissp', 'aws certified',
      'medical license', 'bar exam',
      'security clearance', 'ts/sci',
      'us citizen', 'green card', 'us work authorization required',
      'senior copywriter', 'lead copywriter', 'head of content',
      'director of content', 'vp of marketing',
      'on-site', 'in-office', 'must relocate',
      'fortune 500', 'big 4', 'management consulting'
    ],
    minSalary: 40,
    minMonthly: 8000,
    maxExpYears: 5,
    portfolio: 'https://tinyurl.com/The-Xi-kki-Portfolio'
  },
  {
    id: 'data-annotation',
    name: '🏷️ Data Annotation Specialist',
    titles: [
      'Data Annotator', 'Data Labeler', 'Data Annotation Specialist',
      'AI Training Data Specialist', 'AI Data Trainer',
      'Image Annotator', 'Video Annotator', 'Audio Annotator',
      'Audio Transcriber', 'Transcriptionist',
      'Data Quality Analyst', 'Annotation QA Specialist',
      'Labeling Specialist', 'Data Tagging Specialist',
      'Training Data Curator', 'Data Preparation Specialist',
      'NLP Annotator', 'Text Annotator',
      'Computer Vision Annotator', 'CV Annotator',
      'Content Moderator', 'Content Reviewer',
      'Junior Data Annotator', 'Remote Data Annotator',
      'AI Data Labeler', 'Machine Learning Data Specialist',
      'Data Curator', 'Annotator', 'Labeler',
      'Semantic Segmentation Annotator',
      'Bounding Box Annotator', 'Point Cloud Annotator',
      'Lidar Annotator', '3D Annotator',
      'Prompt Annotator', 'RLHF Data Specialist',
      'AI Feedback Specialist', 'Model Evaluation Specialist',
      'Data Collector', 'Data Enrichment Specialist',
      'Crowdsourcing Coordinator', 'Data Operations Specialist',
      'Data Associate'
    ],
    keywords: [
      'data annotation', 'data labeling', 'data tagging',
      'image annotation', 'video annotation', 'audio annotation',
      'text annotation', 'audio transcription', 'transcription',
      'training data', 'ML data', 'AI training data',
      'data curation', 'data preparation', 'data preprocessing',
      'data cleaning', 'data quality', 'annotation QA',
      'labelbox', 'supervisely', 'CVAT', 'label studio',
      'bounding box', 'semantic segmentation', 'polygon annotation',
      'lidar annotation', 'point cloud', '3D annotation',
      'named entity recognition', 'NER annotation',
      'sentiment annotation', 'sentiment analysis',
      'content moderation', 'content review',
      'NLP annotation', 'computer vision annotation',
      'RLHF', 'human feedback', 'preference annotation',
      'model evaluation', 'AI feedback',
      'data collection', 'data enrichment', 'data ops',
      'crowdsourcing', 'remote annotation',
      'annotation tool', 'annotation platform',
      'image labeling', 'video labeling', 'audio labeling',
      'text labeling', 'data entry annotation',
      'training dataset', 'ground truth',
      'quality control annotation', 'annotation guideline',
      'labeling guideline', 'ontology annotation',
      'classification annotation', 'object detection annotation',
      'OCR annotation', 'keypoint annotation',
      'landmark annotation', 'instance segmentation'
    ],
    skills: [
      'Data Annotation & Labeling', 'Image/Video Annotation',
      'Audio Transcription', 'Text & NLP Annotation',
      'Data Quality Assurance', 'Annotation Tooling (Labelbox, CVAT)',
      'Training Data Curation', 'Content Moderation',
      'RLHF & AI Feedback', 'Data Preparation',
      'Computer Vision Annotation', 'Semantic Segmentation',
      '3D & Point Cloud Annotation', 'Data Operations'
    ],
    rejectionKeywords: [
      'phd', 'doctorate', 'masters degree required',
      '10+ years', '10+ year', 'ten years',
      '15+ years', '15+ year',
      'security clearance', 'ts/sci',
      'us citizen', 'green card', 'us work authorization required',
      'senior software engineer', 'principal engineer',
      'on-site', 'in-office', 'must relocate',
      'medical license', 'bar exam',
      'cissp', 'aws certified',
      'must be a us', 'us person'
    ],
    minSalary: 15,
    minMonthly: 2000,
    maxExpYears: 3,
    portfolio: 'https://tinyurl.com/Ai-Generalist-Portfolio'
  }
];

module.exports = profiles;
